### ISSUE TITLE
Technical SEO Issues

### ISSUE THREAD

**Issue by jdabal** [9ci/9ci.github.io#17]

**Comment by sushantkumbhar9** [comment]
Hi @jdabal 

**Robots.txt**

Need to Disallow our Index of pages, we need to do this because they are showing on Google Search Result.

[https://www.9ci.com/robots.txt](https://www.9ci.com/robots.txt)

check this screenshot
![image](https://user-images.githubusercontent.com/34949030/85192797-78a9c880-b2e1-11ea-8c1b-a666bced1d93.png)

**Sitemap.xml**

Are we giving these services as shown on the given screenshot below?

![image](https://user-images.githubusercontent.com/34949030/85192899-eb1aa880-b2e1-11ea-90b6-68a3db5ff962.png)

**Page Speed**

According to GTMetrix, our Page speed score is 53%.
https://gtmetrix.com/reports/www.9ci.com/44gLk5sm

Check this screenshot
![image](https://user-images.githubusercontent.com/34949030/85193025-a6dbd800-b2e2-11ea-9059-1d219eda3ffa.png)

Need to work on these to fix page speed score
![image](https://user-images.githubusercontent.com/34949030/85193071-c8d55a80-b2e2-11ea-9be3-50b918cbbab6.png)

**Comment by WhitehatSEO-Expert** [comment]
9ci.com - On-Page L2 Recommendation 
https://docs.google.com/document/d/1BCb8-IWJkN-tantowCn2ZMO3Ra0jAE--_0huSwcp0Ao/edit

**Comment by jdabal** [comment]
@sushantkumbhar9  Good document  On-Page L2 Recommendation  but it is a little bit out of date:

1. https://www.9ci.com/robots.txt is not just sitemap.xml

2. Structured Data Schema Markup.  -- what are your suggestions ? I though we did them all. what else have to be done ?
 
3. Browser Compatibility Test -- I thought we talked about it and it was 100% good, Now i see issues using your test tool. Should we fix them? How critical is it?

4.

**Comment by WhitehatSEO-Expert** [comment]
Yes, this is an old report. I was just shifting all my previous work to Github that's why you are seeing an out of date report here. 

Yes, we still need to add sitemap URL in the robots.txt file. This will help Google to index our website changes in a better way. 

You have added structured data but, that is only added on the home page. We need schema on all the pages. I have one relatively effective solution for this. Since we have GTM now, I can create triggers for Structured Data from GTM and it will imply to the whole site quickly. And you don't need to worry about it anywhere. 

With Browser Compatibility, we still do have some issues there. Our website is not fully optimized for different browsers. This is not a critical issue, we can work on it later once we have processed all the other priority tasks.

**Comment by jdabal** [comment]
How about your comment from above:
 Need to Disallow our Index of pages, we need to do this because they are showing on Google Search Result.

What do i have to do ? I don't understand

**Comment by jdabal** [comment]
@sushantkumbhar9 

1. Give me example of what structured data that I should add for example to solutions page https://www.9ci.com/solutions/

2. Robots.txt has schema.xml now

3.  what is "Need to Disallow our Index of pages" ?

![image](https://user-images.githubusercontent.com/421237/85905965-94760880-b7d2-11ea-95de-5d0f2b48c5d7.png)

**Comment by WhitehatSEO-Expert** [comment]
We need to stop Google from showing up these pages types of pages:
http://repo.9ci.com/oss-snapshots/org/grails/plugins/gorm-tools/
http://repo.9ci.com/oss-snapshots/org/grails/

Either we can do this by Google Search Console or with by putting a Robots.txt on repo.9ci.com

**Comment by WhitehatSEO-Expert** [comment]
1. Solutions page won't be a right example. Let me give a better examples..... if I pick a blog post like
https://www.9ci.com/articles/collection-metrics-cei-dso-collection-efficiency-index
I will add a article schema on this page. 

And add logo and social media schema sitewide to be shown up on all pages. 

2. Thanks for the update. 

3. Already replied.

**Comment by jdabal** [comment]
created separate issues for https://github.com/9ci/9ci.github.io/issues/35 and  https://github.com/9ci/9ci.github.io/issues/36
