### ISSUE TITLE
questions on  Monthly SEO Report

### ISSUE THREAD

**Issue by jdabal** [9ci/9ci.github.io#28]
https://datastudio.google.com/u/0/reporting/1O88MIvpgRLHJNjn5gyih08Kd0HNbOtsM/page/L1Q

- [ ] Monthly SEO Report -- Google Analytics

1. How do I edit this report?

2. In "Traffic By Source w/Comparison" why these is no linkedIn ? I clicked multiple times for last 3 weeks on bogs from LinkedIn.

- [ ] Monthly SEO Report -- Google Search Console

1. In website queries "accounts receivable deductions management" shows up on top with the largest Impressions but when I google for it our site is not listed as 23rd link (not counting Ads) , however "automated cash application" is 6th and with little Impressions. Should we use this report to improve keywords and seo? Should we filter by average position ? 

2. How list of queries is generated ? can we edit this list? 

3. Under Website Top Pages -- what does Impression mean?

**Comment by WhitehatSEO-Expert** [comment]
Now, you should be able to see the Social Media Option there. If you tap, only Social Media Traffic, you can see traffic from Social Media channels. We won't be able to just see LinkedIn from that drop down. If you want, I can create one more dashboard dedicated for the LinkedIn traffic. 

Average Search Position reported by Google Search Console is the average position between a time frame. It is not necessary that we are exactly on same position right now. This is just an average...

"automated cash application", is having little impressions because it is less popular keyword than "accounts receivable deductions management". That's why a keyword whose average ranking is less having higher impression.

Yes, this report will help us solve a lot of problems and improve our strategy. We can use it to monitor and decide which keyword to focus on. We can check the CTR for the search terms, we can pick those which higher impressions and lower clicks i.e. low CTR.

We should filter the reports by impressions for now and once we start getting more clicks, we can switch gears to monitoring clicks. 

These queries are discovered by Google based on user searches. Basically, these are the terms for which we showed up on Google or we were clicked by someone. We won't be able to modify this data. You can edit this report, but you won't be able to edit the keywords. 

Under top pages, impression stands for "how many times pages showed up on Google (regardless of whether it was clicked or not). It is filtered in the descending order.

**Comment by jdabal** [comment]
I don't see "Social Media Option there."

How do I edit this report ? Can I add more widgets or remove some ?

**Comment by WhitehatSEO-Expert** [comment]
![Screenshot 2020-06-27 at 4 27 21 AM](https://user-images.githubusercontent.com/67119590/85907262-8229b800-b82e-11ea-8ae1-dee757512439.png)
You can remove some of the fields but, you won't be able add more. Those fields are provided by Google Analytics.
